### ISSUE TITLE
Mismatch between docs and repository for GeoIP config

### ISSUE THREAD

**Issue by kaishin** [plausible/hosting#35] opened 2021-03-11 19:51 UTC
Submitting here since this is not a support request.

In the GeoIP section, the documentation calls the configuration variables `GEOIP_ACCOUNT_KEY` and `GEOIP_LICENSE_KEY`, whereas in this repository they are called `GEOIPUPDATE_ACCOUNT_ID` and `GEOIPUPDATE_LICENSE_KEY` respectively.

**Comment by ukutaht** [comment] 2021-03-12 08:31
Uuf, we've had some issues with people not getting GeoIP to work, I wonder if this is the root cause. Thanks for reporting, I'll fix.

**Comment by ukutaht** [comment] 2021-03-12 08:34
Fixed in https://github.com/plausible/docs/commit/057a7632041d1d4f6caecafc6c8ad25d8dfaefbe

**Closed by ukutaht** 2021-03-12 08:34 UTC

**Comment by kaishin** [comment] 2021-03-15 18:51
> Uuf, we've had some issues with people not getting GeoIP to work, I wonder if this is the root cause. Thanks for reporting, I'll fix.

It certainly was for me 😉 All good now after using the right values.
