### ISSUE TITLE
After upgrade to 2.1.2 login fails

### ISSUE THREAD

**Issue by svandeneertwegh** [plausible/hosting#158] opened 2024-09-26 07:40 UTC
After upgrading to 2.1.2 login fails. I've tried to change password, with success only login still doesnt work.

I reverted back to 2.1.1 and login works.

**Comment by ruslandoga** [comment] 2024-09-26 07:41
👋 @svandeneertwegh 

Thank you for the report! This will probably be fixed with https://github.com/plausible/analytics/pull/4621. I'll try to release v2.1.3 later today.

**Comment by ruslandoga** [comment] 2024-09-26 11:20
v2.1.3 has been released with (hopefully) the fix: https://github.com/plausible/analytics/discussions/4629

**Comment by svandeneertwegh** [comment] 2024-09-26 12:05
@ruslandoga Hi, i tested v2.1.3 and the login works.. But some site views are really slow..

**Comment by ruslandoga** [comment] 2024-09-26 12:10
I also noticed some slowdown recently, for me the cause was that ClickHouse started using more memory and I had swap enabled, so it negatively affected the whole system. What kind of system do you use for hosting Plausible?

**Comment by svandeneertwegh** [comment] 2024-09-26 12:17
Ubuntu 24.04.
I've added the setting 
```
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
``` 
from the beginning to the clickhouse in docker-compose.yml

**Comment by ruslandoga** [comment] 2024-09-26 12:19
Sorry, I meant CPU, RAM, disk type, that kind of thing.

**Comment by svandeneertwegh** [comment] 2024-09-26 12:22
I've got it running on a TransIP VPS with 4GB RAM. I've got next to this a elasticsearch docker setup running en some django apps with uwsgi configurations. It worked perficly with the 2.1.1 i mean the site views so what is changed?

**Comment by ruslandoga** [comment] 2024-09-26 12:25
I am not aware of any changes that could negatively affect performance in Plausible itself, but maybe you could run `docker stats --no-stream` to get a better view of the situation?

**Closed as completed** 2024-09-27 03:40 UTC
